# Generated by Django 3.1 on 2022-05-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20220506_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Completed', 'Completed'), ('Accepted', 'Accepted'), ('Canclelld', 'Cancelled')], default='New', max_length=10),
        ),
    ]
